# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jonramirez\Desktop\TempFiles\Pyproject\UI\main_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(420, 356)
        MainWindow.setMinimumSize(QtCore.QSize(420, 356))
        MainWindow.setMaximumSize(QtCore.QSize(420, 356))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.settingFrame = QtGui.QFrame(self.centralwidget)
        self.settingFrame.setGeometry(QtCore.QRect(10, 10, 400, 300))
        self.settingFrame.setStyleSheet(_fromUtf8("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));"))
        self.settingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.settingFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.settingFrame.setLineWidth(2)
        self.settingFrame.setObjectName(_fromUtf8("settingFrame"))
        self.admin_btn = QtGui.QPushButton(self.settingFrame)
        self.admin_btn.setGeometry(QtCore.QRect(150, 260, 111, 31))
        self.admin_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.admin_btn.setObjectName(_fromUtf8("admin_btn"))
        self.get_data_btn = QtGui.QPushButton(self.settingFrame)
        self.get_data_btn.setGeometry(QtCore.QRect(220, 160, 161, 81))
        self.get_data_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.get_data_btn.setObjectName(_fromUtf8("get_data_btn"))
        self.sensor1_btn = QtGui.QPushButton(self.settingFrame)
        self.sensor1_btn.setGeometry(QtCore.QRect(220, 70, 161, 81))
        self.sensor1_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.sensor1_btn.setObjectName(_fromUtf8("sensor1_btn"))
        self.sensor2_btn = QtGui.QPushButton(self.settingFrame)
        self.sensor2_btn.setGeometry(QtCore.QRect(20, 160, 161, 81))
        self.sensor2_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.sensor2_btn.setObjectName(_fromUtf8("sensor2_btn"))
        self.boyuancy_data_btn = QtGui.QPushButton(self.settingFrame)
        self.boyuancy_data_btn.setGeometry(QtCore.QRect(20, 70, 161, 81))
        self.boyuancy_data_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.boyuancy_data_btn.setObjectName(_fromUtf8("boyuancy_data_btn"))
        self.back_btn = QtGui.QPushButton(self.settingFrame)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.back_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.back_btn.setObjectName(_fromUtf8("back_btn"))
        self.logFrame = QtGui.QFrame(self.centralwidget)
        self.logFrame.setGeometry(QtCore.QRect(10, 10, 400, 300))
        self.logFrame.setStyleSheet(_fromUtf8("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));"))
        self.logFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.logFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.logFrame.setLineWidth(2)
        self.logFrame.setObjectName(_fromUtf8("logFrame"))
        self.weight_edit_log = QtGui.QListView(self.logFrame)
        self.weight_edit_log.setGeometry(QtCore.QRect(20, 60, 361, 192))
        self.weight_edit_log.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.weight_edit_log.setFrameShadow(QtGui.QFrame.Sunken)
        self.weight_edit_log.setLineWidth(2)
        self.weight_edit_log.setObjectName(_fromUtf8("weight_edit_log"))
        self.home_btn = QtGui.QPushButton(self.logFrame)
        self.home_btn.setGeometry(QtCore.QRect(290, 260, 91, 21))
        self.home_btn.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.home_btn.setObjectName(_fromUtf8("home_btn"))
        self.recalibration_btn = QtGui.QPushButton(self.logFrame)
        self.recalibration_btn.setGeometry(QtCore.QRect(20, 260, 91, 21))
        self.recalibration_btn.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.recalibration_btn.setObjectName(_fromUtf8("recalibration_btn"))
        self.userlog_lbl = QtGui.QLabel(self.logFrame)
        self.userlog_lbl.setGeometry(QtCore.QRect(20, 10, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.userlog_lbl.setFont(font)
        self.userlog_lbl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.userlog_lbl.setFrameShape(QtGui.QFrame.Box)
        self.userlog_lbl.setFrameShadow(QtGui.QFrame.Raised)
        self.userlog_lbl.setLineWidth(2)
        self.userlog_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.userlog_lbl.setWordWrap(True)
        self.userlog_lbl.setObjectName(_fromUtf8("userlog_lbl"))
        self.mainFrame = QtGui.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(10, 10, 400, 300))
        self.mainFrame.setAutoFillBackground(False)
        self.mainFrame.setStyleSheet(_fromUtf8("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));"))
        self.mainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.mainFrame.setLineWidth(2)
        self.mainFrame.setObjectName(_fromUtf8("mainFrame"))
        self.start_calibration_btn = QtGui.QPushButton(self.mainFrame)
        self.start_calibration_btn.setGeometry(QtCore.QRect(90, 100, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.start_calibration_btn.setFont(font)
        self.start_calibration_btn.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);"))
        self.start_calibration_btn.setObjectName(_fromUtf8("start_calibration_btn"))
        self.settings_btn = QtGui.QPushButton(self.mainFrame)
        self.settings_btn.setGeometry(QtCore.QRect(338, 1, 61, 61))
        self.settings_btn.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.settings_btn.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/gear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn.setIcon(icon)
        self.settings_btn.setIconSize(QtCore.QSize(60, 60))
        self.settings_btn.setObjectName(_fromUtf8("settings_btn"))
        self.loadingFrame = QtGui.QFrame(self.centralwidget)
        self.loadingFrame.setGeometry(QtCore.QRect(10, 10, 400, 300))
        self.loadingFrame.setStyleSheet(_fromUtf8("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));"))
        self.loadingFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.loadingFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.loadingFrame.setLineWidth(2)
        self.loadingFrame.setObjectName(_fromUtf8("loadingFrame"))
        self.calibration_progbar = QtGui.QProgressBar(self.loadingFrame)
        self.calibration_progbar.setGeometry(QtCore.QRect(25, 130, 350, 40))
        self.calibration_progbar.setStyleSheet(_fromUtf8(""))
        self.calibration_progbar.setProperty("value", 24)
        self.calibration_progbar.setTextVisible(False)
        self.calibration_progbar.setObjectName(_fromUtf8("calibration_progbar"))
        self.loadingFrame.raise_()
        self.settingFrame.raise_()
        self.logFrame.raise_()
        self.mainFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionProcedure = QtGui.QAction(MainWindow)
        self.actionProcedure.setObjectName(_fromUtf8("actionProcedure"))
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionProcedure)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.settings_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.settingFrame.show)
        QtCore.QObject.connect(self.settings_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.mainFrame.hide)
        QtCore.QObject.connect(self.start_calibration_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.mainFrame.hide)
        QtCore.QObject.connect(self.start_calibration_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.loadingFrame.show)
        QtCore.QObject.connect(self.recalibration_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logFrame.hide)
        QtCore.QObject.connect(self.recalibration_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.loadingFrame.show)
        QtCore.QObject.connect(self.home_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.logFrame.hide)
        QtCore.QObject.connect(self.home_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.mainFrame.show)
        QtCore.QObject.connect(self.back_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.settingFrame.hide)
        QtCore.QObject.connect(self.back_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.mainFrame.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Balancing Test", None))
        self.admin_btn.setText(_translate("MainWindow", "Admin", None))
        self.get_data_btn.setText(_translate("MainWindow", "Download Calibration", None))
        self.sensor1_btn.setText(_translate("MainWindow", "Calibrate Sensor 1", None))
        self.sensor2_btn.setText(_translate("MainWindow", "Calibrate Sensor 2", None))
        self.boyuancy_data_btn.setText(_translate("MainWindow", "Edit Bouyacny Data", None))
        self.back_btn.setText(_translate("MainWindow", "Back", None))
        self.home_btn.setText(_translate("MainWindow", "Home", None))
        self.recalibration_btn.setText(_translate("MainWindow", "Start", None))
        self.userlog_lbl.setText(_translate("MainWindow", "Place weights in the corrsiponding areas given from the Log below.", None))
        self.start_calibration_btn.setText(_translate("MainWindow", "Start", None))
        self.menuAbout.setTitle(_translate("MainWindow", "More", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionProcedure.setText(_translate("MainWindow", "Procedure", None))

import images_rc
