# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logFrame = QtWidgets.QFrame(self.centralwidget)
        self.logFrame.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.logFrame.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.logFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.logFrame.setLineWidth(2)
        self.logFrame.setObjectName("logFrame")
        self.weight_edit_log = QtWidgets.QListView(self.logFrame)
        self.weight_edit_log.setGeometry(QtCore.QRect(20, 61, 741, 281))
        self.weight_edit_log.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.weight_edit_log.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.weight_edit_log.setLineWidth(2)
        self.weight_edit_log.setObjectName("weight_edit_log")
        self.home_btn = QtWidgets.QPushButton(self.logFrame)
        self.home_btn.setGeometry(QtCore.QRect(640, 370, 121, 31))
        self.home_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.home_btn.setObjectName("home_btn")
        self.recalibration_btn = QtWidgets.QPushButton(self.logFrame)
        self.recalibration_btn.setGeometry(QtCore.QRect(20, 370, 121, 31))
        self.recalibration_btn.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.recalibration_btn.setObjectName("recalibration_btn")
        self.userlog_lbl = QtWidgets.QLabel(self.logFrame)
        self.userlog_lbl.setGeometry(QtCore.QRect(20, 10, 741, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.userlog_lbl.setFont(font)
        self.userlog_lbl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.userlog_lbl.setFrameShape(QtWidgets.QFrame.Box)
        self.userlog_lbl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.userlog_lbl.setLineWidth(2)
        self.userlog_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.userlog_lbl.setWordWrap(True)
        self.userlog_lbl.setObjectName("userlog_lbl")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.mainFrame.setAutoFillBackground(False)
        self.mainFrame.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mainFrame.setLineWidth(2)
        self.mainFrame.setObjectName("mainFrame")
        self.start_calibration_btn = QtWidgets.QPushButton(self.mainFrame)
        self.start_calibration_btn.setGeometry(QtCore.QRect(270, 170, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.start_calibration_btn.setFont(font)
        self.start_calibration_btn.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.start_calibration_btn.setObjectName("start_calibration_btn")
        self.settings_btn = QtWidgets.QPushButton(self.mainFrame)
        self.settings_btn.setGeometry(QtCore.QRect(720, 1, 61, 61))
        self.settings_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/images/gear.png);")
        self.settings_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn.setIcon(icon)
        self.settings_btn.setIconSize(QtCore.QSize(60, 60))
        self.settings_btn.setObjectName("settings_btn")
        self.loadingFrame = QtWidgets.QFrame(self.centralwidget)
        self.loadingFrame.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.loadingFrame.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.loadingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadingFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.loadingFrame.setLineWidth(2)
        self.loadingFrame.setObjectName("loadingFrame")
        self.calibration_progbar = QtWidgets.QProgressBar(self.loadingFrame)
        self.calibration_progbar.setGeometry(QtCore.QRect(19, 200, 741, 40))
        self.calibration_progbar.setStyleSheet("")
        self.calibration_progbar.setProperty("value", 24)
        self.calibration_progbar.setTextVisible(False)
        self.calibration_progbar.setObjectName("calibration_progbar")
        self.calibration_progbar.raise_()
        self.settingFrame = QtWidgets.QFrame(self.centralwidget)
        self.settingFrame.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.settingFrame.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.settingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.settingFrame.setLineWidth(2)
        self.settingFrame.setObjectName("settingFrame")
        self.admin_btn = QtWidgets.QPushButton(self.settingFrame)
        self.admin_btn.setGeometry(QtCore.QRect(700, 10, 61, 21))
        self.admin_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.admin_btn.setObjectName("admin_btn")
        self.get_data_btn = QtWidgets.QPushButton(self.settingFrame)
        self.get_data_btn.setGeometry(QtCore.QRect(310, 380, 161, 31))
        self.get_data_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.get_data_btn.setObjectName("get_data_btn")
        self.back_btn = QtWidgets.QPushButton(self.settingFrame)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.back_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.back_btn.setObjectName("back_btn")
        self.sensor1_btn = QtWidgets.QPushButton(self.settingFrame)
        self.sensor1_btn.setGeometry(QtCore.QRect(30, 60, 139, 31))
        self.sensor1_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor1_btn.setObjectName("sensor1_btn")
        self.sensor2_btn = QtWidgets.QPushButton(self.settingFrame)
        self.sensor2_btn.setGeometry(QtCore.QRect(30, 110, 139, 31))
        self.sensor2_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor2_btn.setObjectName("sensor2_btn")
        self.salinity_cbox = QtWidgets.QCheckBox(self.settingFrame)
        self.salinity_cbox.setGeometry(QtCore.QRect(590, 77, 141, 17))
        self.salinity_cbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_cbox.setObjectName("salinity_cbox")
        self.program_mode_lbl = QtWidgets.QLabel(self.settingFrame)
        self.program_mode_lbl.setGeometry(QtCore.QRect(590, 57, 141, 21))
        self.program_mode_lbl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.program_mode_lbl.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.program_mode_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.program_mode_lbl.setObjectName("program_mode_lbl")
        self.foam_cbox = QtWidgets.QCheckBox(self.settingFrame)
        self.foam_cbox.setEnabled(False)
        self.foam_cbox.setGeometry(QtCore.QRect(590, 94, 141, 16))
        self.foam_cbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foam_cbox.setObjectName("foam_cbox")
        self.save_cailbration = QtWidgets.QCheckBox(self.settingFrame)
        self.save_cailbration.setEnabled(False)
        self.save_cailbration.setGeometry(QtCore.QRect(590, 110, 141, 16))
        self.save_cailbration.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.save_cailbration.setObjectName("save_cailbration")
        self.label = QtWidgets.QLabel(self.settingFrame)
        self.label.setGeometry(QtCore.QRect(190, 30, 81, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setObjectName("label")
        self.salinity_mode_1 = QtWidgets.QRadioButton(self.settingFrame)
        self.salinity_mode_1.setGeometry(QtCore.QRect(590, 180, 141, 17))
        self.salinity_mode_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_mode_1.setChecked(True)
        self.salinity_mode_1.setObjectName("salinity_mode_1")
        self.salinity_mode_2 = QtWidgets.QRadioButton(self.settingFrame)
        self.salinity_mode_2.setEnabled(True)
        self.salinity_mode_2.setGeometry(QtCore.QRect(590, 197, 141, 16))
        self.salinity_mode_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_mode_2.setObjectName("salinity_mode_2")
        self.salinity_mode_3 = QtWidgets.QRadioButton(self.settingFrame)
        self.salinity_mode_3.setEnabled(True)
        self.salinity_mode_3.setGeometry(QtCore.QRect(590, 213, 141, 16))
        self.salinity_mode_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_mode_3.setObjectName("salinity_mode_3")
        self.program_mode_lbl_2 = QtWidgets.QLabel(self.settingFrame)
        self.program_mode_lbl_2.setGeometry(QtCore.QRect(590, 160, 141, 21))
        self.program_mode_lbl_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.program_mode_lbl_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.program_mode_lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.program_mode_lbl_2.setObjectName("program_mode_lbl_2")
        self.salinity_mode_4 = QtWidgets.QRadioButton(self.settingFrame)
        self.salinity_mode_4.setEnabled(True)
        self.salinity_mode_4.setGeometry(QtCore.QRect(590, 229, 141, 16))
        self.salinity_mode_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_mode_4.setObjectName("salinity_mode_4")
        self.label_2 = QtWidgets.QLabel(self.settingFrame)
        self.label_2.setGeometry(QtCore.QRect(500, 250, 81, 41))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setObjectName("label_2")
        self.sensor1_set_btn = QtWidgets.QPushButton(self.settingFrame)
        self.sensor1_set_btn.setGeometry(QtCore.QRect(30, 60, 139, 31))
        self.sensor1_set_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor1_set_btn.setObjectName("sensor1_set_btn")
        self.sensor2_set_btn = QtWidgets.QPushButton(self.settingFrame)
        self.sensor2_set_btn.setGeometry(QtCore.QRect(30, 110, 139, 31))
        self.sensor2_set_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor2_set_btn.setObjectName("sensor2_set_btn")
        self.lb1_input_sbox = QtWidgets.QSpinBox(self.settingFrame)
        self.lb1_input_sbox.setGeometry(QtCore.QRect(190, 60, 81, 31))
        self.lb1_input_sbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb1_input_sbox.setObjectName("lb1_input_sbox")
        self.lb2_input_sbox = QtWidgets.QSpinBox(self.settingFrame)
        self.lb2_input_sbox.setGeometry(QtCore.QRect(190, 110, 81, 31))
        self.lb2_input_sbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb2_input_sbox.setObjectName("lb2_input_sbox")
        self.salinity_input_dsbox = QtWidgets.QDoubleSpinBox(self.settingFrame)
        self.salinity_input_dsbox.setGeometry(QtCore.QRect(590, 250, 141, 41))
        self.salinity_input_dsbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_input_dsbox.setObjectName("salinity_input_dsbox")
        self.screen_calibrate = QtWidgets.QPushButton(self.settingFrame)
        self.screen_calibrate.setGeometry(QtCore.QRect(50, 230, 211, 41))
        self.screen_calibrate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.screen_calibrate.setObjectName("screen_calibrate")
        self.admin_btn.raise_()
        self.get_data_btn.raise_()
        self.back_btn.raise_()
        self.salinity_cbox.raise_()
        self.program_mode_lbl.raise_()
        self.foam_cbox.raise_()
        self.save_cailbration.raise_()
        self.label.raise_()
        self.salinity_mode_1.raise_()
        self.salinity_mode_2.raise_()
        self.salinity_mode_3.raise_()
        self.program_mode_lbl_2.raise_()
        self.salinity_mode_4.raise_()
        self.label_2.raise_()
        self.sensor1_set_btn.raise_()
        self.sensor2_set_btn.raise_()
        self.sensor2_btn.raise_()
        self.sensor1_btn.raise_()
        self.lb1_input_sbox.raise_()
        self.lb2_input_sbox.raise_()
        self.salinity_input_dsbox.raise_()
        self.screen_calibrate.raise_()
        self.salinity_ask_frame = QtWidgets.QFrame(self.centralwidget)
        self.salinity_ask_frame.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.salinity_ask_frame.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.salinity_ask_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.salinity_ask_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.salinity_ask_frame.setLineWidth(2)
        self.salinity_ask_frame.setObjectName("salinity_ask_frame")
        self.salinity_input_dsbox_2 = QtWidgets.QDoubleSpinBox(self.salinity_ask_frame)
        self.salinity_input_dsbox_2.setGeometry(QtCore.QRect(360, 200, 141, 41))
        self.salinity_input_dsbox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_input_dsbox_2.setObjectName("salinity_input_dsbox_2")
        self.salinity_mode_5 = QtWidgets.QRadioButton(self.salinity_ask_frame)
        self.salinity_mode_5.setEnabled(True)
        self.salinity_mode_5.setGeometry(QtCore.QRect(360, 147, 141, 16))
        self.salinity_mode_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_mode_5.setObjectName("salinity_mode_5")
        self.salinity_mode_6 = QtWidgets.QRadioButton(self.salinity_ask_frame)
        self.salinity_mode_6.setEnabled(True)
        self.salinity_mode_6.setGeometry(QtCore.QRect(360, 163, 141, 16))
        self.salinity_mode_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_mode_6.setObjectName("salinity_mode_6")
        self.salinity_mode_7 = QtWidgets.QRadioButton(self.salinity_ask_frame)
        self.salinity_mode_7.setEnabled(True)
        self.salinity_mode_7.setGeometry(QtCore.QRect(360, 179, 141, 16))
        self.salinity_mode_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_mode_7.setObjectName("salinity_mode_7")
        self.salinity_mode_8 = QtWidgets.QRadioButton(self.salinity_ask_frame)
        self.salinity_mode_8.setGeometry(QtCore.QRect(360, 130, 141, 17))
        self.salinity_mode_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.salinity_mode_8.setChecked(True)
        self.salinity_mode_8.setAutoExclusive(True)
        self.salinity_mode_8.setObjectName("salinity_mode_8")
        self.program_mode_lbl_3 = QtWidgets.QLabel(self.salinity_ask_frame)
        self.program_mode_lbl_3.setGeometry(QtCore.QRect(360, 110, 141, 21))
        self.program_mode_lbl_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.program_mode_lbl_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.program_mode_lbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.program_mode_lbl_3.setObjectName("program_mode_lbl_3")
        self.label_3 = QtWidgets.QLabel(self.salinity_ask_frame)
        self.label_3.setGeometry(QtCore.QRect(270, 200, 81, 41))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setObjectName("label_3")
        self.submit_salinity = QtWidgets.QPushButton(self.salinity_ask_frame)
        self.submit_salinity.setGeometry(QtCore.QRect(290, 300, 211, 41))
        self.submit_salinity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.submit_salinity.setObjectName("submit_salinity")
        self.calibration_ask_frame = QtWidgets.QFrame(self.centralwidget)
        self.calibration_ask_frame.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.calibration_ask_frame.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.7, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.calibration_ask_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calibration_ask_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.calibration_ask_frame.setLineWidth(2)
        self.calibration_ask_frame.setObjectName("calibration_ask_frame")
        self.lb1_input_sbox_2 = QtWidgets.QSpinBox(self.calibration_ask_frame)
        self.lb1_input_sbox_2.setGeometry(QtCore.QRect(420, 170, 81, 31))
        self.lb1_input_sbox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb1_input_sbox_2.setObjectName("lb1_input_sbox_2")
        self.sensor1_set_btn_2 = QtWidgets.QPushButton(self.calibration_ask_frame)
        self.sensor1_set_btn_2.setGeometry(QtCore.QRect(260, 170, 139, 31))
        self.sensor1_set_btn_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor1_set_btn_2.setObjectName("sensor1_set_btn_2")
        self.sensor2_btn_2 = QtWidgets.QPushButton(self.calibration_ask_frame)
        self.sensor2_btn_2.setGeometry(QtCore.QRect(120, 220, 139, 31))
        self.sensor2_btn_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor2_btn_2.setObjectName("sensor2_btn_2")
        self.sensor1_btn_2 = QtWidgets.QPushButton(self.calibration_ask_frame)
        self.sensor1_btn_2.setGeometry(QtCore.QRect(120, 170, 139, 31))
        self.sensor1_btn_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor1_btn_2.setObjectName("sensor1_btn_2")
        self.sensor2_set_btn_2 = QtWidgets.QPushButton(self.calibration_ask_frame)
        self.sensor2_set_btn_2.setGeometry(QtCore.QRect(260, 220, 139, 31))
        self.sensor2_set_btn_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor2_set_btn_2.setObjectName("sensor2_set_btn_2")
        self.lb2_input_sbox_2 = QtWidgets.QSpinBox(self.calibration_ask_frame)
        self.lb2_input_sbox_2.setGeometry(QtCore.QRect(420, 220, 81, 31))
        self.lb2_input_sbox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lb2_input_sbox_2.setObjectName("lb2_input_sbox_2")
        self.label_4 = QtWidgets.QLabel(self.calibration_ask_frame)
        self.label_4.setGeometry(QtCore.QRect(420, 140, 81, 21))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setObjectName("label_4")
        self.submit_calibration = QtWidgets.QPushButton(self.calibration_ask_frame)
        self.submit_calibration.setGeometry(QtCore.QRect(290, 300, 211, 41))
        self.submit_calibration.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.submit_calibration.setObjectName("submit_calibration")
        self.sensor2_set_btn_2.raise_()
        self.lb1_input_sbox_2.raise_()
        self.sensor1_set_btn_2.raise_()
        self.sensor2_btn_2.raise_()
        self.sensor1_btn_2.raise_()
        self.lb2_input_sbox_2.raise_()
        self.label_4.raise_()
        self.submit_calibration.raise_()
        self.loadingFrame.raise_()
        self.settingFrame.raise_()
        self.salinity_ask_frame.raise_()
        self.calibration_ask_frame.raise_()
        self.logFrame.raise_()
        self.mainFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionProcedure = QtWidgets.QAction(MainWindow)
        self.actionProcedure.setObjectName("actionProcedure")
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionProcedure)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.back_btn.clicked.connect(self.settingFrame.hide)
        self.recalibration_btn.clicked.connect(self.loadingFrame.show)
        self.home_btn.clicked.connect(self.logFrame.hide)
        self.recalibration_btn.clicked.connect(self.logFrame.hide)
        self.back_btn.clicked.connect(self.mainFrame.show)
        self.home_btn.clicked.connect(self.mainFrame.show)
        self.start_calibration_btn.clicked.connect(self.mainFrame.hide)
        self.start_calibration_btn.clicked.connect(self.loadingFrame.show)
        self.settings_btn.clicked.connect(self.settingFrame.show)
        self.settings_btn.clicked.connect(self.mainFrame.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Balancing Test"))
        self.home_btn.setText(_translate("MainWindow", "Home"))
        self.recalibration_btn.setText(_translate("MainWindow", "Start"))
        self.userlog_lbl.setText(_translate("MainWindow", "Place weights in the corresponding areas given from the Log below."))
        self.start_calibration_btn.setText(_translate("MainWindow", "Start"))
        self.admin_btn.setText(_translate("MainWindow", "Admin"))
        self.get_data_btn.setText(_translate("MainWindow", "Download Calibration Results"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.sensor1_btn.setText(_translate("MainWindow", "Calibrate load cell 1"))
        self.sensor2_btn.setText(_translate("MainWindow", "Calibrate load cell 2"))
        self.salinity_cbox.setText(_translate("MainWindow", "Ask for Salinity"))
        self.program_mode_lbl.setText(_translate("MainWindow", "Program Mode"))
        self.foam_cbox.setText(_translate("MainWindow", "Foam Compatiablity"))
        self.save_cailbration.setText(_translate("MainWindow", "Save Calibration"))
        self.label.setText(_translate("MainWindow", "  Input Weight "))
        self.salinity_mode_1.setText(_translate("MainWindow", "Deep Water: 34.9 PPM"))
        self.salinity_mode_2.setText(_translate("MainWindow", "Coastal Water: 31 PPM"))
        self.salinity_mode_3.setText(_translate("MainWindow", "Fresh Water: 0 PPM"))
        self.program_mode_lbl_2.setText(_translate("MainWindow", "Salinty Mode"))
        self.salinity_mode_4.setText(_translate("MainWindow", "Other"))
        self.label_2.setText(_translate("MainWindow", "  Input Salinity"))
        self.sensor1_set_btn.setText(_translate("MainWindow", "Set Cell 1"))
        self.sensor2_set_btn.setText(_translate("MainWindow", "Set Cell 2"))
        self.screen_calibrate.setText(_translate("MainWindow", "Run Calibrate Screen"))
        self.salinity_mode_5.setText(_translate("MainWindow", "Coastal Water: 31 PPM"))
        self.salinity_mode_6.setText(_translate("MainWindow", "Fresh Water: 0 PPM"))
        self.salinity_mode_7.setText(_translate("MainWindow", "Other"))
        self.salinity_mode_8.setText(_translate("MainWindow", "Deep Water: 34.9 PPM"))
        self.program_mode_lbl_3.setText(_translate("MainWindow", "Salinty Mode"))
        self.label_3.setText(_translate("MainWindow", "  Input Salinity"))
        self.submit_salinity.setText(_translate("MainWindow", "Submit"))
        self.sensor1_set_btn_2.setText(_translate("MainWindow", "Set Cell 1"))
        self.sensor2_btn_2.setText(_translate("MainWindow", "Calibrate load cell 2"))
        self.sensor1_btn_2.setText(_translate("MainWindow", "Calibrate load cell 1"))
        self.sensor2_set_btn_2.setText(_translate("MainWindow", "Set Cell 2"))
        self.label_4.setText(_translate("MainWindow", "  Input Weight "))
        self.submit_calibration.setText(_translate("MainWindow", "Submit"))
        self.menuAbout.setTitle(_translate("MainWindow", "More"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionProcedure.setText(_translate("MainWindow", "Procedure"))

# import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

